fatal: [Lab2]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 192.168.0.5 closed.\r\n", "module_stdout": "\r\n\r\nTraceback (most recent call last): \r\n  File \"/home/lupton/.ansible/tmp/ansible-tmp-1670204094.4414968-28238-28708172980790/AnsiballZ_docker_container.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/lupton/.ansible/tmp/ansible-tmp-1670204094.4414968-28238-28708172980790/AnsiballZ_docker_container.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/lupton/.ansible/tmp/ansible-tmp-1670204094.4414968-28238-28708172980790/AnsiballZ_docker_container.py\", line 47, in invoke_module\r\n    runpy.run_module(mod_name='ansible_collections.community.docker.plugins.modules.docker_container', init_globals=dict(_module_fqn='ansible_collections.community.docker.plugins.modules.docker_container', _modlib_path=modlib_path),\r\n  File \"/usr/lib/python3.10/runpy.py\", line 224, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib/python3.10/runpy.py\", line 96, in _run_module_code\r\n    _run_code(code, mod_globals, init_globals,\r\n  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_docker_container_payload_8qa3e7jv/ansible_docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 3714, in <module>\r\n  File \"/tmp/ansible_docker_container_payload_8qa3e7jv/ansible_docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 3703, in main\r\n  File \"/tmp/ansible_docker_container_payload_8qa3e7jv/ansible_docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 2859, in __init__\r\n  File \"/tmp/ansible_docker_container_payload_8qa3e7jv/ansible_docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 1473, in __init__\r\n  File \"/tmp/ansible_docker_container_payload_8qa3e7jv/ansible_docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 1965, in _parse_ulimits\r\nValueError: invalid literal for int() with base 10: \" 'esnet'}\"\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}


fatal: [Lab2]: FAILED! => {"changed": false, "msg": "Error starting container 33a129e4fd9f7ccbfe3acff26469b80b0b9ff00074c91af7769b971f35833f6b:  
500 Server Error for http+docker://localhost/v1.41/containers/33a129e4fd9f7ccbfe3acff26469b80b0b9ff00074c91af7769b971f35833f6b/start:
Internal Server Error (\"failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error setting rlimits for ready process: error setting rlimit type 7: invalid argument: unknown\")"}
