Lupton <olross19@gmail.com>
	
12:19 PM (8 minutes ago)
	
to oliver.ross
fatal: [Lab2]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 192.168.0.5 closed.\r\n", "module_stdout": "\r\nTraceback (most recent ca   _ansiballz_main()\r\n  File \"/home/lupton/.ansible/tmp/ansible-tmp-1670202694.0384786-27098-201645433890444/AnsiballZ_docker_container.py\", line 99, in 33890444/AnsiballZ_docker_container.py\", line 47, in invoke_module\r\n    runpy.run_module(mod_name='ansible_collections.community.docker.plugins.modules.dousr/lib/python3.10/runpy.py\", line 224, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib/python3.10n    exec(code, run_globals)\r\n  File \"/tmp/ansible_docker_container_payload_1215bt83/ansible_docker_container_payload.zip/ansible_collections/community/doip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 3703, in main\r\n  File \"/tmp/ansible_docker_container_payload_1215bt83/_docker_container_payload_1215bt83/ansible_docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 1473es/docker_container.py\", line 1965, in _parse_ulimits\r\nValueError: invalid literal for int() with base 10: \" 'esnet'}\"\r\n", "msg": "MODULE FAILURE\nSee
	
